### ISSUE TITLE
fix code examples in NORM.md

### ISSUE THREAD

**Issue by cndofx** [libospl/libospl#37]
Some of the code examples wouldn't compile as they are written. Functions will implicitly return their last expression, so functions like this should be fixed either by removing the semicolon or removing the return value:
```rust
fn my_second() -> i32
{
	2;
}
```
error[[E0308]](https://doc.rust-lang.org/stable/error-index.html#E0308): mismatched types
```
 --> src/lib.rs:1:19
  |
1 | fn my_second() -> i32 
  |    ---------      ^^^ expected `i32`, found `()`
  |    |
  |    implicitly returns `()` as its body has no tail or `return` expression
2 | {
3 |     2;
  |      - help: remove this semicolon

For more information about this error, try `rustc --explain E0308`.
```
I can do this myself later in a PR if you'd like.

**Comment by AngeloFrangione** [comment]
Hi, thank you for opening an issue on ospl

In which examples does this occur ? There are no examples with a return value

I would be glad if you open a PR

**Comment by Sulfiore** [comment]
Hi thank you for opening an issue on OSPL

I will fix it quickly
